namespace ScannerHelper
{

    public enum Tok {
        EOF = 0,
        LINE_BREAK,
        COMMA,
        ID,
        INUM,
        PLUS,
        MINUS,
        MULT,
        DIVISION,
        ASSIGN,
        SET,
        STREAM,
        LEFT_SQUARE_BRACKET,
        RIGHT_SQUARE_BRACKET,
        LEFT_BRACKET,
        RIGHT_BRACKET,
        IF,
        ELSE,
        WHILE,
        SUB,
        RETURN,
        END,
        AND,
        OR,
        NOT,
        IS,
        LT,
        GT,
        LEQ,
        GEQ,
        NEQ,
        ADDRESS,
        STRING,
        CHAR,
        ECHO,
        MOD,
        DIV,
        ONE_LINE_CMNT,
        MULT_LINE_CMNT,
    };
}